package com.example.career_recommendation.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * RecommendationResult — stores the ranked career suggestions for a student.
 * Generated by RecommendationServiceImpl and persisted for history.
 */
@Entity
@Table(name = "recommendation_result")
@Data
@EqualsAndHashCode(callSuper = false)
public class RecommendationResult extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "recommendation_id")
    private Long recommendationId;

    @ManyToOne
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    @ManyToOne
    @JoinColumn(name = "career_id", nullable = false)
    private Career career;

    @Column(name = "total_score")
    private double totalScore;

    /** 1 = best match */
    private int rank;
}
